'use strict';

const sb = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// Admin sessions are intentionally scoped to admin.html. If an authenticated admin lands on the public site, sign out immediately.
(async()=>{try{const {data}=await sb.auth.getSession();if(data.session && sessionStorage.getItem('tidyline_admin_active')==='1'){sessionStorage.removeItem('tidyline_admin_active');await sb.auth.signOut();}}catch(e){console.warn('Admin session guard:',e)}})();
let settingsState={company_name:'Tidyline',logo_url:null,price_standard:45,price_deep:65,price_moveinout:55,price_office:50,currency:'USD'};
const CURRENCIES={USD:{symbol:'$',name:'US Dollar'},GHS:{symbol:'GH₵',name:'Ghana Cedi'},EUR:{symbol:'€',name:'Euro'},GBP:{symbol:'£',name:'British Pound'}};
function money(v){const c=CURRENCIES[settingsState.currency]||CURRENCIES.USD;return `${c.symbol}${Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;}
const $=id=>document.getElementById(id);
const esc=s=>{const d=document.createElement('div');d.textContent=s??'';return d.innerHTML};
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),3200)}
function fmtDate(v){return new Date(v+'T00:00:00').toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'})}
function fmtTime(v){if(!v)return '';const [h,m]=v.split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`}
function durationHours(a,b){if(!a||!b)return 0;let [ah,am]=a.split(':').map(Number),[bh,bm]=b.split(':').map(Number);let n=(bh*60+bm)-(ah*60+am);return n<0?n+1440:n? n/60:0}
function applyBranding(){const n='Tidyline';$('brandName').textContent=n;$('footerBrand').textContent=n;$('footerBrandSmall').textContent=n;document.title=`${n} — Professional cleaning, simply booked`;[['rate_standard',settingsState.price_standard],['rate_deep',settingsState.price_deep],['rate_moveinout',settingsState.price_moveinout],['rate_office',settingsState.price_office]].forEach(([id,v])=>$(id).textContent=`${(CURRENCIES[settingsState.currency]||CURRENCIES.USD).symbol}${Number(v||0).toFixed(0)}/hr`)}
async function loadSettings(){try{const {data}=await sb.from('settings').select('*').eq('id',1).single();if(data)settingsState=data}catch(e){console.warn(e)}applyBranding()}
function updateEstimate(){const hrs=durationHours($('f_start').value,$('f_end').value);const type=$('f_type').value;const rate={"Standard clean":settingsState.price_standard,"Deep clean":settingsState.price_deep,"Move-in / move-out":settingsState.price_moveinout,"Office clean":settingsState.price_office}[type]||0;if(hrs){$('durationPreview').textContent=`${hrs.toFixed(1)} hour${hrs===1?'':'s'} × ${money(rate)}/hr`;$('pricePreview').textContent=money(hrs*Number(rate))}else{$('durationPreview').textContent='Select a time window';$('pricePreview').textContent='—'}}
async function sendBookingEmail(booking){try{const {error}=await sb.functions.invoke('send-email',{body:{type:'booking_confirmation',booking,currency:settingsState.currency||'USD',companyName:'Tidyline'}});if(error)throw error;return true}catch(e){console.error(e);return false}}
$('bookingForm').addEventListener('input',updateEstimate);$('bookingForm').addEventListener('change',updateEstimate);
$('bookingForm').addEventListener('submit',async e=>{e.preventDefault();const start=$('f_start').value,end=$('f_end').value,date=$('f_date').value;if(!start||!end||start>=end){toast('Please choose a valid start and end time.');return}if(!date||date<new Date().toISOString().slice(0,10)){toast('Please choose a future service date.');return}const email=$('f_email').value.trim();if(!/^\S+@\S+\.\S+$/.test(email)){toast('Please enter a valid email address.');return}const btn=$('submitBtn');btn.disabled=true;btn.innerHTML='Processing booking…';const id='b_'+Date.now()+'_'+Math.random().toString(36).slice(2,8);const draft={id,name:$('f_name').value.trim(),phone:$('f_phone').value.trim(),email,address:$('f_address').value.trim(),date,start,end,type:$('f_type').value,notes:$('f_notes').value.trim()};try{const {data,error}=await sb.rpc('create_booking',{p_id:id,p_name:draft.name,p_phone:draft.phone,p_email:draft.email,p_address:draft.address,p_date:draft.date,p_start:start,p_end:end,p_type:draft.type,p_notes:draft.notes});if(error)throw error;const r=Array.isArray(data)?data[0]:data;if(!r)throw new Error('No booking result returned.');$('bookingCard').hidden=true;$('confirmCard').hidden=false;$('confirmTitle').textContent=`Thanks, ${draft.name.split(' ')[0]||'there'}.`;$('confirmDetail').textContent=`${draft.type} on ${fmtDate(draft.date)} from ${fmtTime(start)} to ${fmtTime(end)} at ${draft.address}.`;$('confirmRef').textContent=r.booking_ref||r.assigned_booking_ref||id;$('confirmStaff').textContent='Pending admin assignment';$('confirmPrice').textContent=money(r.price);const sent=await sendBookingEmail({email:draft.email,name:draft.name,phone:draft.phone,type:draft.type,date:draft.date,start_time:start,end_time:end,address:draft.address,price:r.price,booking_ref:r.booking_ref||id,status:'pending'});if(!sent)toast('Booking confirmed, but the email could not be sent.');$('confirmCard').scrollIntoView({behavior:'smooth',block:'center'})}catch(err){console.error(err);toast(err.message||'We could not create your booking. Please try again.')}finally{btn.disabled=false;btn.innerHTML='Confirm booking request <span>→</span>'}});

// Public-site interactions: scroll reveals, animated proof counters and service-card shortcuts.
function initHomeInteractions(){
  const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObserver.unobserve(e.target)}}),{threshold:.12});
  document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
  const counterObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,target=Number(el.dataset.target||0);let start=0,step=Math.max(1,Math.ceil(target/24));const tick=()=>{start=Math.min(target,start+step);el.textContent=start;if(start<target)requestAnimationFrame(tick)};tick();counterObserver.unobserve(el)}),{threshold:.7});
  document.querySelectorAll('.count').forEach(el=>counterObserver.observe(el));
  document.querySelectorAll('.service-card').forEach(card=>card.addEventListener('click',e=>{if(e.target.closest('a'))return;const type=card.dataset.service;if($('f_type')){$('f_type').value=type;updateEstimate();$('book').scrollIntoView({behavior:'smooth'})}}));
  document.querySelectorAll('[data-quick-service]').forEach(link=>link.addEventListener('click',()=>{const type=link.dataset.quickService;if($('f_type')){$('f_type').value=type;updateEstimate()}}));
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initHomeInteractions);else initHomeInteractions();

function resetBooking(){$('bookingForm').reset();$('bookingCard').hidden=false;$('confirmCard').hidden=true;$('f_date').min=new Date().toISOString().slice(0,10);updateEstimate();$('book').scrollIntoView({behavior:'smooth'})}
window.resetBooking=resetBooking;$('year').textContent=new Date().getFullYear();$('f_date').min=new Date().toISOString().slice(0,10);loadSettings().then(updateEstimate);
