const {createClient}=window.supabase;
const sb=createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
let staffMember=null, myJobs=[], availabilityRequests=[]; let timer=null, timerStart=null; const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){const e=$('toast');e.textContent=msg;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),2800)}
function fmtDate(v){return v?new Date(v+'T00:00:00').toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'}):'—'}
function fmtTime(v){if(!v)return'—';const [h,m]=v.split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`}
function durationMinutes(start,end){if(!start||!end)return 0;const a=start.split(':').map(Number),b=end.split(':').map(Number);let x=(b[0]*60+b[1])-(a[0]*60+a[1]);if(x<0)x+=1440;return x}
function hoursFor(jobs){return jobs.reduce((s,j)=>s+durationMinutes(j.start_time,j.end_time),0)/60}
function money(v){return new Intl.NumberFormat(undefined,{style:'currency',currency:'GHS',maximumFractionDigits:2}).format(Number(v||0))}
function statusLabel(s){return String(s||'').replace('_',' ').replace(/\b\w/g,x=>x.toUpperCase())}
function switchStaffView(id){document.querySelectorAll('.staff-view').forEach(v=>{v.hidden=v.id!==id;v.classList.toggle('active',v.id===id)});document.querySelectorAll('.staff-nav').forEach(b=>b.classList.toggle('active',b.dataset.staffView===id));window.scrollTo({top:0,behavior:'smooth'})}
function bindNavigation(){document.querySelectorAll('[data-staff-view]').forEach(b=>b.addEventListener('click',()=>switchStaffView(b.dataset.staffView)));$('availabilityHomeBtn').onclick=()=>switchStaffView('staffAvailability');$('refreshStaff').onclick=loadStaffData;document.querySelectorAll('[data-job-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-job-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderJobs(b.dataset.jobFilter)})}
async function login(e){e.preventDefault();$('staffLoginError').textContent='';$('staffLoginBtn').disabled=true;try{const {error}=await sb.auth.signInWithPassword({email:$('staffEmail').value.trim(),password:$('staffPassword').value});if(error)throw error;await startPortal()}catch(err){$('staffLoginError').textContent=err.message||'Unable to sign in.'}finally{$('staffLoginBtn').disabled=false}}
async function startPortal(){const {data:{user}}=await sb.auth.getUser();if(!user){showLogin();return}const {data,error}=await sb.rpc('get_my_staff_profile');if(error||!data){await sb.auth.signOut();$('staffLoginError').textContent='This account is not linked to a Tidyline staff profile. Ask an administrator to link your account.';showLogin();return}staffMember=Array.isArray(data)?data[0]:data;if(!staffMember){showLogin();return}$('staffLogin').hidden=true;$('staffApp').hidden=false;$('staffGreeting').textContent=`Good ${new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}, ${staffMember.name.split(' ')[0]}`;updateStatus();await loadStaffData();bindNavigation();}
function showLogin(){$('staffLogin').hidden=false;$('staffApp').hidden=true}
function updateStatus(){const s=staffMember.current_status||'available';$('staffStatusPill').textContent=`● ${statusLabel(s)}`;$('currentAvailabilityTitle').textContent=statusLabel(s);$('currentAvailabilityBadge').textContent=statusLabel(s);$('currentAvailabilityBadge').className=`availability-badge ${s}`;$('currentAvailabilityText').textContent=s==='available'?'You are currently available for assignment.':`Current status: ${statusLabel(s)}.`}
async function loadStaffData(){const [jobs,reqs]=await Promise.all([sb.rpc('get_my_staff_bookings'),sb.rpc('get_my_availability_requests')]);if(jobs.error){toast(jobs.error.message);myJobs=[]}else myJobs=jobs.data||[];if(reqs.error){toast(reqs.error.message);availabilityRequests=[]}else availabilityRequests=reqs.data||[];renderAll()}
function renderAll(){renderStats();renderToday();renderJobs('active');renderHours();renderAvailability()}
function renderStats(){const today=new Date().toISOString().slice(0,10),month=today.slice(0,7);const todayJobs=myJobs.filter(j=>j.date===today&&j.status!=='cancelled');const completed=myJobs.filter(j=>j.status==='completed');const monthJobs=completed.filter(j=>String(j.date).startsWith(month));const h=hoursFor(completed);$('staffStats').innerHTML=[['Today',todayJobs.length,'Assigned jobs'],['Completed',completed.length,'All time'],['This month',hoursFor(monthJobs).toFixed(1)+'h','Recorded hours'],['Revenue',money(monthJobs.reduce((s,j)=>s+Number(j.price||0),0)),'Completed jobs']].map(x=>`<article class="staff-stat"><small>${x[0]}</small><strong>${x[1]}</strong><span>${x[2]}</span></article>`).join('');}
function jobCard(j){const active=['assigned','in_progress'].includes(j.status);return `<article class="job-card"><div class="job-top"><div><strong>${esc(j.booking_ref||j.id)}</strong><small>${esc(j.type||'Service')}</small></div><span class="job-status ${esc(j.status)}">${statusLabel(j.status)}</span></div><div class="job-meta"><div><small>Customer</small><strong>${esc(j.name)}</strong></div><div><small>When</small><strong>${fmtDate(j.date)} · ${fmtTime(j.start_time)}</strong></div><div><small>Duration</small><strong>${j.start_time&&j.end_time?durationMinutes(j.start_time,j.end_time)+' min':'Scheduled'}</strong></div></div><div class="job-actions"><button class="btn btn-secondary btn-sm" data-open-job="${esc(j.id)}">View job</button>${j.status==='assigned'?`<button class="btn btn-primary btn-sm" data-start-job="${esc(j.id)}">Start job</button>`:''}${j.status==='in_progress'?`<button class="btn btn-primary btn-sm" data-complete-job="${esc(j.id)}">Complete job</button>`:''}</div></article>`}
function renderToday(){const today=new Date().toISOString().slice(0,10);const rows=myJobs.filter(j=>j.date===today&&j.status!=='cancelled').sort((a,b)=>a.start_time.localeCompare(b.start_time));$('todayJobs').innerHTML=rows.length?rows.map(jobCard).join(''):`<div class="compact-row"><div><strong>No jobs scheduled today.</strong><small>You're all caught up.</small></div></div>`;bindJobButtons($('todayJobs'))}
function renderJobs(filter='active'){let rows=myJobs.slice();if(filter==='active')rows=rows.filter(j=>['assigned','in_progress'].includes(j.status));if(filter==='completed')rows=rows.filter(j=>j.status==='completed');rows.sort((a,b)=>`${b.date}${b.start_time}`.localeCompare(`${a.date}${a.start_time}`));$('allJobs').innerHTML=rows.length?rows.map(jobCard).join(''):`<div class="compact-row"><div><strong>No ${filter==='active'?'active ':''}jobs found.</strong><small>New assignments will appear here.</small></div></div>`;bindJobButtons($('allJobs'))}
function bindJobButtons(root){root.querySelectorAll('[data-open-job]').forEach(b=>b.onclick=()=>openJob(b.dataset.openJob));root.querySelectorAll('[data-start-job]').forEach(b=>b.onclick=()=>changeJobStatus(b.dataset.startJob,'start'));root.querySelectorAll('[data-complete-job]').forEach(b=>b.onclick=()=>changeJobStatus(b.dataset.completeJob,'complete'))}
function openJob(id){const j=myJobs.find(x=>x.id===id);if(!j)return;const canStart=j.status==='assigned',canComplete=j.status==='in_progress';$('jobModalContent').innerHTML=`<div class="job-detail"><span class="eyebrow">Booking ${esc(j.booking_ref||j.id)}</span><h2 id="jobModalTitle">${esc(j.type||'Service')}</h2><p>${esc(j.name)} · ${fmtDate(j.date)} · ${fmtTime(j.start_time)}</p><div class="detail-grid"><div class="detail-box"><small>Customer</small><strong>${esc(j.name)}</strong></div><div class="detail-box"><small>Phone</small><strong>${esc(j.phone||'—')}</strong></div><div class="detail-box"><small>Address</small><strong>${esc(j.address||'—')}</strong></div><div class="detail-box"><small>Price</small><strong>${money(j.price)}</strong></div></div><div class="detail-box"><small>Notes</small><strong>${esc(j.notes||'No special instructions.')}</strong></div>${j.status==='in_progress'?`<div class="timer-box"><small>Job in progress</small><strong id="jobTimer">00:00:00</strong></div>`:''}<div class="job-actions" style="margin-top:18px">${canStart?`<button class="btn btn-primary" data-modal-start="${esc(j.id)}">Start job</button>`:''}${canComplete?`<button class="btn btn-primary" data-modal-complete="${esc(j.id)}">Complete job</button>`:''}<button class="btn btn-secondary" data-close-job>Close</button></div></div>`;$('jobModal').hidden=false;$('jobModal').querySelectorAll('[data-close-job]').forEach(b=>b.onclick=closeJob);const st=$('jobModal').querySelector('[data-modal-start]');if(st)st.onclick=()=>changeJobStatus(id,'start');const co=$('jobModal').querySelector('[data-modal-complete]');if(co)co.onclick=()=>changeJobStatus(id,'complete');if(j.status==='in_progress')startTimer(j.started_at)}
function closeJob(){stopTimer();$('jobModal').hidden=true}
function startTimer(startedAt){stopTimer();timerStart=startedAt?new Date(startedAt):new Date();const draw=()=>{const sec=Math.max(0,Math.floor((Date.now()-timerStart.getTime())/1000));const h=String(Math.floor(sec/3600)).padStart(2,'0'),m=String(Math.floor(sec%3600/60)).padStart(2,'0'),s=String(sec%60).padStart(2,'0');const el=$('jobTimer');if(el)el.textContent=`${h}:${m}:${s}`};draw();timer=setInterval(draw,1000)}
function stopTimer(){clearInterval(timer);timer=null;timerStart=null}
async function changeJobStatus(id,action){const fn=action==='start'?'start_my_job':'complete_my_job';const {data,error}=await sb.rpc(fn,{p_booking_id:id});if(error){toast(error.message);return}toast(action==='start'?'Job started. Time is now being recorded.':'Job completed. Your hours have been recorded.');closeJob();await loadStaffData()}
function renderHours(){const today=new Date().toISOString().slice(0,10),month=today.slice(0,7),completed=myJobs.filter(j=>j.status==='completed');const weekStartDate=new Date();const day=(weekStartDate.getDay()+6)%7;weekStartDate.setDate(weekStartDate.getDate()-day);const ws=weekStartDate.toISOString().slice(0,10);const week=completed.filter(j=>j.date>=ws&&j.date<=today),monthJobs=completed.filter(j=>String(j.date).startsWith(month));const cards=[['This week',hoursFor(week).toFixed(2)+' h'],['This month',hoursFor(monthJobs).toFixed(2)+' h'],['Jobs completed',monthJobs.length],['Revenue',money(monthJobs.reduce((s,j)=>s+Number(j.price||0),0))]];$('hoursSummary').innerHTML=cards.map(c=>`<article class="earning-card"><small>${c[0]}</small><strong>${c[1]}</strong></article>`).join('');$('completedJobs').innerHTML=monthJobs.length?monthJobs.sort((a,b)=>b.date.localeCompare(a.date)).map(j=>`<div class="compact-row"><div><strong>${esc(j.booking_ref||j.id)}</strong><small>${fmtDate(j.date)} · ${esc(j.type||'Service')}</small></div><div style="text-align:right"><strong>${durationMinutes(j.start_time,j.end_time)} min</strong><small>${money(j.price)}</small></div></div>`).join(''):`<div class="compact-row"><div><strong>No completed jobs this month.</strong><small>Completed work will appear here.</small></div></div>`}
function renderAvailability(){const r=availabilityRequests;$('availabilityHistory').innerHTML=r.length?r.map(x=>`<div class="request-row"><div><strong>${statusLabel(x.status)}</strong><small>${fmtDate(x.start_date)} → ${fmtDate(x.end_date)}</small><small>${esc(x.reason||'No reason provided')}</small></div><span class="request-status ${esc(x.approval_status)}">${esc(x.approval_status)}</span></div>`).join(''):`<div class="compact-row"><div><strong>No requests yet.</strong><small>Your availability requests will appear here.</small></div></div>`}
async function submitAvailability(e){e.preventDefault();const start=$('availabilityStart').value,end=$('availabilityEnd').value;if(end<start){toast('End date must be on or after start date.');return}const status=$('availabilityStatus').value,reason=$('availabilityReason').value.trim();const {data,error}=await sb.rpc('submit_staff_availability_request',{p_status:status,p_start_date:start,p_end_date:end,p_reason:reason});if(error){toast(error.message);return}$('availabilityForm').reset();toast('Availability request submitted for Admin approval.');await loadStaffData()}
$('staffLoginForm').addEventListener('submit',login);$('staffLogout').onclick=async()=>{await sb.auth.signOut();showLogin();toast('Signed out.')};$('availabilityForm').addEventListener('submit',submitAvailability);document.querySelectorAll('[data-close-job]').forEach(b=>b.onclick=closeJob);sb.auth.getSession().then(({data})=>{if(data.session)startPortal()});
